"""add_budgets

Revision ID: 1d6ed0d05c43
Revises: dc9f7ff0ddf4
Create Date: 2026-06-01 22:00:34.403169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6ed0d05c43'
down_revision: Union[str, None] = 'dc9f7ff0ddf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False, comment='预算年份'),
    sa.Column('month', sa.Integer(), nullable=False, comment='预算月份 (1-12)'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='分类名称（如"餐饮"、"交通"）'),
    sa.Column('amount', sa.Float(), nullable=False, comment='预算金额（正数）'),
    sa.Column('note', sa.String(length=200), nullable=True, comment='备注说明'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', 'category', name='uq_budget_ymc')
    )
    op.create_index(op.f('ix_budgets_id'), 'budgets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budgets_id'), table_name='budgets')
    op.drop_table('budgets')
    # ### end Alembic commands ###
