"""add_chat_sessions

Revision ID: b9aab5c0bb03
Revises: 0338cffdfef1
Create Date: 2026-05-31 18:54:20.345466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9aab5c0bb03'
down_revision: Union[str, None] = '0338cffdfef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_key', sa.String(length=32), nullable=False, comment='对外暴露的会话标识（12位 hex）'),
    sa.Column('messages', sa.JSON(), nullable=False, comment='OpenAI 格式的消息历史 [{role, content, ...}]'),
    sa.Column('persona', sa.String(length=20), nullable=True, comment='当前会话的角色风格'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='会话创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='最后活跃时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_session_key'), 'chat_sessions', ['session_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_session_key'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
